apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-sgdx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-jkwx-tenant/test-app-qldh/devfile-sample-python-basic-sgdx@sha256:1a7ac1c8a809743526ba6deb760a271be73ddf66ce399902beafd0354b0e8a1c
        name: my-python
        resources: {}
status: {}
