apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-sgdx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-sgdx
    app.kubernetes.io/part-of: test-app-qldh
  name: devfile-sample-python-basic-sgdx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-sgdx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-sgdx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-jkwx-tenant/test-app-qldh/devfile-sample-python-basic-sgdx@sha256:1a7ac1c8a809743526ba6deb760a271be73ddf66ce399902beafd0354b0e8a1c
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
